#Testing Simple-JWT
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###
#Testing Simple-JWT = Token Refresh
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MzA1MDE5OSwiaWF0IjoxNzYyOTYzNzk5LCJqdGkiOiI0NWM4Nzc2NzYyYTE0NDI0YTk0MzgzM2U5OWQyNmE3OCIsInVzZXJfaWQiOiIxIn0.YYDlz6R7wRkha6OspnouqIkAMc246MBfSErf8yu3rJ0"
}

###
# Authenticated to show self.orders
GET http://127.0.0.1:8000/my-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MzA1MDE5OSwiaWF0IjoxNzYyOTYzNzk5LCJqdGkiOiI0NWM4Nzc2NzYyYTE0NDI0YTk0MzgzM2U5OWQyNmE3OCIsInVzZXJfaWQiOiIxIn0.YYDlz6R7wRkha6OspnouqIkAMc246MBfSErf8yu3rJ0


###
#Get All Products
GET http://127.0.0.1:8000/products/gen/ HTTP/1.1


###
POST http://127.0.0.1:8000/products/gen/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY3MTgwLCJpYXQiOjE3NjI5NjY4ODAsImp0aSI6IjhjOTk1ZTg3ZWM1NjQyNDhiODczNTE4NTY1NzQ2ZGQ5IiwidXNlcl9pZCI6IjEifQ.YZ-Wn_9DxEB0KNziY8ptR4hDxCXrm4H7RPmRGCqyk6U

{
    "description": "Clothes",
    "name": "Choes",
    "price": "300.2",
    "stock": 1
}
###

PUT http://127.0.0.1:8000/products/apiv/22/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY3MTgwLCJpYXQiOjE3NjI5NjY4ODAsImp0aSI6IjhjOTk1ZTg3ZWM1NjQyNDhiODczNTE4NTY1NzQ2ZGQ5IiwidXNlcl9pZCI6IjEifQ.YZ-Wn_9DxEB0KNziY8ptR4hDxCXrm4H7RPmRGCqyk6U

{
    "description": "Clothes",
    "name": "Gloves",
    "price": "13.99",
    "stock": 0
}

###
DELETE http://127.0.0.1:8000/products/apiv/22/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTY3MTgwLCJpYXQiOjE3NjI5NjY4ODAsImp0aSI6IjhjOTk1ZTg3ZWM1NjQyNDhiODczNTE4NTY1NzQ2ZGQ5IiwidXNlcl9pZCI6IjEifQ.YZ-Wn_9DxEB0KNziY8ptR4hDxCXrm4H7RPmRGCqyk6U

###



