GET http://127.0.0.1:8000/products/gen/ HTTP/1.1

###
POST http://127.0.0.1:8000/products/gen/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTU3OTIyLCJpYXQiOjE3NjI5NTc2MjIsImp0aSI6IjRjMjg5N2JkMTcxZjQxZjY5YjkzYTExZjY1N2Q3MmY1IiwidXNlcl9pZCI6IjIifQ.onav29T5amKkQpN0joXJ2kGSbcAAMH20XKdAkB6SMhg

{
    "description": "Electronics",
    "name": "Air Conditioner",
    "price": "22000.99",
    "stock": 1
}

###
#Testing Simple-JWT
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "password": "1234"
}

###
# Authenticated to show self.orders
GET http://127.0.0.1:8000/my-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTU4MTk4LCJpYXQiOjE3NjI5NTc4OTgsImp0aSI6IjUxMDlhZmMwYTM2MTQzYzdhYzA4YTgzNjVlNjk0MTk1IiwidXNlcl9pZCI6IjIifQ.UjFw8KwOneFbgPanZL2nsVdGHWrad4rzkQPnttILbeY